### ISSUE TITLE
How to use Jarvis and LLM icon?

### ISSUE THREAD

**Issue by jamesbraza** [KirillRepinArt/ChatGPT-UI#3]
Here is how my chat looks (no profile pictures):

![screenshot of chat](https://github.com/KirillRepinArt/ChatGPT-UI/assets/8990777/f1f19d64-a8ce-485c-b48f-516c4e16c500)

It looks like your install somehow used [Jarvis.card_03.png](https://github.com/KirillRepinArt/ChatGPT-UI/blob/main/Jarvis.card_03.png).

How are you using Jarvis and LLM icon with text-generation-webui?

**Comment by KirillRepinArt** [comment]
It's fairly straight forward, [Jarvis](https://github.com/KirillRepinArt/ChatGPT-UI/blob/main/Jarvis.card_03.png) is a character card, you can download it, launch the UI, go to `Parameters/ Upload character/TavernAI PNG`, open the character card there and click `Submit`.

Now you should be seeing the greeting message from Jarvis on a Chat page, and he is also available in the `Parameters/Character` page.
You can set your own profile picture in this section also.

As for LLM icon:
![TextGen_wip_08](https://github.com/KirillRepinArt/ChatGPT-UI/assets/118350327/eba259d4-f7c5-4810-ae23-912a3269f218)

1. Download LLM icon  
2. Create a shortcut for `start_windows.bat`
3.  In the properties of this shortcut you can change the look of this shortcut to the `LLM_Icon.ico
` file.
Not sure how would it work on Mac, but I suppose it wouldn't be much different.

**Comment by jamesbraza** [comment]
I just played around with that now and I see how it works.  Thank you!

Feel free to close this out, or add to the README
