### ISSUE TITLE
Ability to disable "ChatGPT Interface" in background?

### ISSUE THREAD

**Issue by jamesbraza** [KirillRepinArt/ChatGPT-UI#4]
<img width="178" alt="ChatGPT Interface screenshot" src="https://github.com/KirillRepinArt/ChatGPT-UI/assets/8990777/75630234-124f-495c-9d5e-2c387f994486">

Is there some way to disable the "ChatGPT Interface" text in the background of the chat?

(I am naming my AI something besides ChatGPT)

**Comment by KirillRepinArt** [comment]
You might have to do manually inside the CSS file.
```
/* BACKGROUND */
.gradio-container {
    background-color: #343541 !important;
    padding: 0 !important;
    background-image: url('data:image
```
In the background section, you'd need to remove `background-image: url...` line.

**Comment by jamesbraza** [comment]
Ah okay, I figured it'd be that.  Is there some way this CSS's text can be parameterized, instead of being a static base64 encoded image?

Otherwise, feel free to close this out
